# Generated by Django 2.0 on 2018-01-17 07:13

from django.db import migrations, models
import django.db.models.fields
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('blog_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('blog_title', models.CharField(max_length=500)),
                ('blog_text', models.TextField()),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('publish_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=400)),
                ('user_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AddField(
            model_name='blog',
            name='author_id',
            field=models.ForeignKey(on_delete=django.db.models.fields.CharField, to='personal_blog.User'),
        ),
    ]
