# Generated by Django 2.0 on 2018-01-18 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal_blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='author_id',
            new_name='author',
        ),
    ]
